[tool.poetry]
name = "asyncio_tutorial"
version = "0.1.0"
description = "Asyncio tutorial."
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hackersandslackers/asyncio-tutorial/"
repository = "https://github.com/hackersandslackers/asyncio-tutorial/"
documentation = "https://github.com/hackersandslackers/asyncio-tutorial/"
keywords = [
  "Asyncio",
  "Aiohttp",
  "Aiofiles",
  "Asynchronous",
  "I/O"
]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "*"
asyncio = "*"
aiofiles = "*"
loguru = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
mock = "*"
mypy = "*"
black = "^20.8b1"
isort = "*"
flake8 = "^3.9.0"

[tool.poetry.scripts]
run = "asgi:app"

[tool.poetry.urls]
issues = "https://github.com/hackersandslackers/asyncio-tutorial/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
